## Bruce Benedict M. Gonzalvo
## 2ECEA

## NORMALIZATION PROBLEM: 
Normalization is one of the most basic preprocessing techniques in 
data analytics. This involves centering and scaling process. Centering means subtracting the data from the 
mean and scaling means dividing with its standard deviation. Mathematically, normalization can be 
expressed as: 
𝑍 = 𝑋 − 𝑥̅/𝜎
In Python, element-wise mean and element-wise standard deviation can be obtained by using .mean() and 
.std() calls. 
In this problem, create a random 5 x 5 ndarray and store it to variable X. Normalize X. Save your normalized 
ndarray as X_normalized.npy

In [84]:
#Imports the numpy library gives it an alias '.np'
import numpy as np

In [85]:
#This creates a 5 by 5 grid (like a small table) where each spot in the table gets a random number between 0 and almost 1, like 0.5 or 0.8
X = np.random.random((5,5))

In [86]:
#This finds the average (or middle) number of all the numbers in my grid.
mean = X.mean()

In [87]:
#This computes the standard deviation of the array X. 
std_dev = X.std()

In [88]:
#This changes all your numbers so they are adjusted around the number zero, making it easier to compare them. This is like adjusting weights so they balance perfectly on a seesaw.
X_normalized = (X - mean)/std_dev

In [89]:
#This saves the normalized array
np.save('X_normalized', X_normalized)

In [90]:
#load and display the normalized array
normalized_array = np.load('X_normalized.npy')
print(normalized_array)

[[-0.04503018  1.69606898  1.16888859  0.02916578  0.07150913]
 [-1.41685988  0.73527623  0.71740381  1.28831265  0.31447698]
 [-1.42992439 -0.1846542   0.63147492  0.71273664 -0.57246075]
 [-0.74272091  0.44847375  1.33722067  0.80811488 -1.11704572]
 [-1.5237509  -1.82983825 -1.25582661  0.75504888 -0.59606007]]


## DIVISIBLE BY 3 PROBLEM: Create the following 10 x 10 ndarray.
𝐴 =
[1 4 ⋯ 81 100
⋮ ⋮ ⋱ ⋮ ⋮
⋮ ⋮ ⋱ ⋮ ⋮
⋮ ⋮ ⋱ ⋮ ⋮
8281 8464 ⋯ 9801 10000]
which are the squares of the first 100 positive integers. 
From this ndarray, determine all the elements that are divisible by 3. Save the result as div_by_3.npy

In [91]:
import numpy as np

In [92]:
#This function creates an array. Inside, there's a list comprehension ([i**2 for i in range(1, 101)]) that generates the squares of numbers from 1 to 100.
squares = np.array([i**2 for i in range(1,101)])

In [93]:
#This reshapes the list of 100 numbers into a 10x10 matrix
A = squares.reshape(10,10)

In [94]:
#This checks each number in array A to see if it has no remainder when divided by 3 (which means it's divisible by 3).
divisible_by_3 = A[A % 3 == 0]

In [95]:
#This saves the filtered numbers to a file named
np.save('div_by_3.npy', divisible_by_3)

In [96]:
#Load the .npy file back into Python and print it to check what’s inside.
load_data = np.load('div_by_3.npy')
print(load_data)

[   9   36   81  144  225  324  441  576  729  900 1089 1296 1521 1764
 2025 2304 2601 2916 3249 3600 3969 4356 4761 5184 5625 6084 6561 7056
 7569 8100 8649 9216 9801]
