## Bruce Benedict M. Gonzalvo
## 2ECEA

## NORMALIZATION PROBLEM: 
Normalization is one of the most basic preprocessing techniques in 
data analytics. This involves centering and scaling process. Centering means subtracting the data from the 
mean and scaling means dividing with its standard deviation. Mathematically, normalization can be 
expressed as: 
𝑍 = 𝑋 − 𝑥̅/𝜎
In Python, element-wise mean and element-wise standard deviation can be obtained by using .mean() and 
.std() calls. 
In this problem, create a random 5 x 5 ndarray and store it to variable X. Normalize X. Save your normalized 
ndarray as X_normalized.npy

In [101]:
#Imports the numpy library gives it an alias '.np'
import numpy as np

In [102]:
#Test the mean and standard deviation calculations of a given array.Ensures that computed values match expected values for accuracy verification.
def test_mean_std_dev():
    # create a test array
    test_array = np.array([1, 2, 3 ,4, 5])
    
    # define the expected mean and standard deviation
    expected_mean = 3
    expected_std_dev = np.std(test_array)
    
    # compute the mean and standard deviation of the test array
    computed_mean = test_array.mean()
    computed_std_dev = test_array.std()

    # check if the computed_mean matches expected_mean
    # if not, raise an AssertionError with the message "Mean test failed."
    assert computed_mean == expected_mean,"Mean test failed."
    
    # verify that computed_std_dev equals expected_std_dev
    # if this assertion fails, raise an AssertionError with the message "Standard deviation test failed."
    assert computed_std_dev == expected_std_dev, "Standard deviation test failed."

test_mean_std_dev()

In [103]:
# set the random seed to ensure reproducibility
np.random.seed(42)

In [104]:
#Generates a 5 x 5 matrix of random numbers between 0 and 1
X = np.random.rand(5,5)

In [105]:
#Calculate the mean of the matrix 
mean = X.mean()

In [106]:
#Calculate the standard deviation of the matrix 
std_dev = X.std()

In [107]:
#Normalized the matrix so that its mean is 0 and its standard deviation is 1
X_normalized = (X - mean)/std_dev

In [108]:
#Save the matrix to the file 'X_normalized.npy'
np.save('X_normalized.npy', X_normalized)

In [109]:
#Load the normalized matrix from 'X_normalized.npy', handling errors gracefully
try:
    normalized_array = np.load('X_normalized.npy')
    
    print(normalized_array)
    
except FileNotFoundError:

    print("Error: The file 'X_normalized.npy' does not exist.")
    
except Exception as e:

    print(f"An error occurred: {e}")

[[-0.23709911  1.82467557  1.04200929  0.56488331 -1.01905371]
 [-1.01914002 -1.36950322  1.52216525  0.57367372  0.95640937]
 [-1.5036896   1.89336468  1.40145369 -0.81751722 -0.92670866]
 [-0.92105645 -0.48865218  0.30043311 -0.03168212 -0.5352181 ]
 [ 0.61209803 -1.07818578 -0.53194206 -0.26636415  0.05464636]]


## DIVISIBLE BY 3 PROBLEM: Create the following 10 x 10 ndarray.
𝐴 =
[1 4 ⋯ 81 100
⋮ ⋮ ⋱ ⋮ ⋮
⋮ ⋮ ⋱ ⋮ ⋮
⋮ ⋮ ⋱ ⋮ ⋮
8281 8464 ⋯ 9801 10000]
which are the squares of the first 100 positive integers. 
From this ndarray, determine all the elements that are divisible by 3. Save the result as div_by_3.npy

In [52]:
#Create a 10 x 10 array of squares of the numbers from 1 to 100
A = (np.arange(1, 101)**2).reshape(10, 10)
A

array([[    1,     4,     9,    16,    25,    36,    49,    64,    81,
          100],
       [  121,   144,   169,   196,   225,   256,   289,   324,   361,
          400],
       [  441,   484,   529,   576,   625,   676,   729,   784,   841,
          900],
       [  961,  1024,  1089,  1156,  1225,  1296,  1369,  1444,  1521,
         1600],
       [ 1681,  1764,  1849,  1936,  2025,  2116,  2209,  2304,  2401,
         2500],
       [ 2601,  2704,  2809,  2916,  3025,  3136,  3249,  3364,  3481,
         3600],
       [ 3721,  3844,  3969,  4096,  4225,  4356,  4489,  4624,  4761,
         4900],
       [ 5041,  5184,  5329,  5476,  5625,  5776,  5929,  6084,  6241,
         6400],
       [ 6561,  6724,  6889,  7056,  7225,  7396,  7569,  7744,  7921,
         8100],
       [ 8281,  8464,  8649,  8836,  9025,  9216,  9409,  9604,  9801,
        10000]])

In [53]:
#Filter the array to include only elements divisible by 3 
divisible_by_3 = A[A % 3 == 0]

In [54]:
#Save the filtered array to the file 'div_by_3.npy'.
np.save('div_by_3.npy', divisible_by_3)
divisible_by_3

array([   9,   36,   81,  144,  225,  324,  441,  576,  729,  900, 1089,
       1296, 1521, 1764, 2025, 2304, 2601, 2916, 3249, 3600, 3969, 4356,
       4761, 5184, 5625, 6084, 6561, 7056, 7569, 8100, 8649, 9216, 9801])

In [55]:
#Load and print the .npy file to verify its contents 
load_data = np.load('div_by_3.npy')
print(load_data)

[   9   36   81  144  225  324  441  576  729  900 1089 1296 1521 1764
 2025 2304 2601 2916 3249 3600 3969 4356 4761 5184 5625 6084 6561 7056
 7569 8100 8649 9216 9801]
